name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Extract version from release tag
        id: extract_version
        run: |
          # Get the release tag (e.g., v1.2.3 or 1.2.3)
          TAG="${{ github.event.release.tag_name }}"
          # Remove 'v' prefix if present
          VERSION="${TAG#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update package.json version
        run: |
          pnpm version ${{ steps.extract_version.outputs.version }} --no-git-tag-version

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version bump
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package.json pnpm-lock.yaml
          git commit -m "chore: bump version to ${{ steps.extract_version.outputs.version }} [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main || echo "Nothing to push"
